runtime: php72
service: id-grabber
runtime_config:
  document_root: public

beta_settings:
  # for Cloud SQL, set this value to the Cloud SQL connection name,
  # e.g. "project:region:cloudsql-instance"
  cloud_sql_instances: "informationprovider-224113:europe-west3:information-provider"

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: "IdGrabber-Y2lf60xpbnYVtdL7ZEhI"
  APP_DEBUG: true
  APP_ENV: production
  STORAGE_DIR: /tmp
  # Насройки базы данных
  DB_HOST: localhost
  DB_DATABASE: parser
  DB_USERNAME: root
  DB_PASSWORD: Pandurata121086
  DB_SOCKET: /cloudsql/informationprovider-224113:europe-west3:information-provider
  # Настройки приложения ВК
  VK_APP_ID: 6772171
  VK_SECRET_KEY: glbsCBkX6XCQDUFrhtaO
  # Настройки приложения ОК
  OK_APP_ID: 1274036480
  OK_SECRET_KEY: 0B2848F885A311B1EA39F624
  OK_PUBLIC_KEY: CBACEBPMEBABABABA
  CACHE_DRIVER: database
  TOKEN_SERVICE: "https://token-manager-dot-informationprovider-224113.appspot.com/v1/"
  SERVICE_ID_GRABBER_URL: "informationprovider-224113.appspot.com"
  GOOGLE_PROJECT_ID: "informationprovider-224113"

liveness_check:
  path: "/livenessCheck"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/readinessCheck"
  check_interval_sec: 8
  timeout_sec: 7
  failure_threshold: 2
  success_threshold: 3
  app_start_timeout_sec: 180

automatic_scaling:
  min_instances: 6
  min_idle_instances: 10